# Generated by Django 3.1.4 on 2020-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('severity', models.PositiveIntegerField(choices=[(1, 'info'), (2, 'warning'), (3, 'danger')], default=1)),
                ('text', models.TextField()),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('hide_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='weekday',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday'), (8, 'Work days'), (9, 'Public holiday')], verbose_name='Weekday'),
        ),
    ]
