# Generated by Django 3.1.4 on 2021-01-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0004_tag_tagconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagconnection',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Child Weight'),
        ),
    ]
