# Generated by Django 3.1.4 on 2021-01-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0007_auto_20210109_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagconnection',
            name='child',
        ),
        migrations.RemoveField(
            model_name='tagconnection',
            name='parent',
        ),
        migrations.AddField(
            model_name='tagconnection',
            name='subordinate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subordinate', to='cajovyobchudek.tag', verbose_name='Child Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagconnection',
            name='superior',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='superior', to='cajovyobchudek.tag', verbose_name='Parent Tag'),
            preserve_default=False,
        ),
    ]
