# Generated by Django 3.1.4 on 2021-01-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0008_auto_20210109_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagconnection',
            name='subordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superiors', to='cajovyobchudek.tag', verbose_name='Child Tag'),
        ),
        migrations.AlterField(
            model_name='tagconnection',
            name='superior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='cajovyobchudek.tag', verbose_name='Parent Tag'),
        ),
    ]
