# Generated by Django 3.1.5 on 2021-01-10 11:40

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0011_tag_description_rendered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='description_rendered', verbose_name='Description'),
        ),
    ]
