# Generated by Django 3.1.5 on 2021-01-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0015_auto_20210130_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cajovyobchudek.product', verbose_name='Product')),
            ],
        ),
    ]
