# Generated by Django 3.1.5 on 2021-01-30 15:46

import cajovyobchudek.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0016_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='name',
            field=cajovyobchudek.models.fields.NameField(default='', max_length=63, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productusage',
            name='name',
            field=cajovyobchudek.models.fields.NameField(default='', max_length=63, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
