# Generated by Django 3.1.5 on 2021-01-30 15:51

import cajovyobchudek.models.shop
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0017_auto_20210130_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='product',
            field=cajovyobchudek.models.shop.ProductLink(on_delete=django.db.models.deletion.CASCADE, to='cajovyobchudek.product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', cajovyobchudek.models.shop.ProductLink(on_delete=django.db.models.deletion.CASCADE, to='cajovyobchudek.product', verbose_name='Product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cajovyobchudek.tag', verbose_name='Tag')),
            ],
        ),
    ]
