# Generated by Django 3.1.5 on 2021-01-30 16:32

import cajovyobchudek.models.shop
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0020_producttag_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='product',
            field=cajovyobchudek.models.shop.ProductLink(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cajovyobchudek.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=cajovyobchudek.models.shop.ProductLink(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='cajovyobchudek.product', verbose_name='Product'),
        ),
    ]
