# Generated by Django 3.1.5 on 2021-01-30 22:15

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0021_auto_20210130_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cajovyobchudek.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Tag Weight'),
        ),
        migrations.DeleteModel(
            name='TagConnection',
        ),
    ]
