# Generated by Django 3.1.5 on 2021-01-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0022_auto_20210130_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='main_menu',
            field=models.BooleanField(default=False, help_text='Main menu items will appear in the page layout', verbose_name='Main menu'),
        ),
    ]
