# Generated by Django 3.1.5 on 2021-01-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0024_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(related_name='_product_variants_+', to='cajovyobchudek.Product'),
        ),
    ]
