# Generated by Django 3.1.5 on 2021-02-21 16:36

import cajovyobchudek.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0025_product_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=cajovyobchudek.models.fields.FaculativeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='cajovyobchudek.productdescription', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=cajovyobchudek.models.fields.FaculativeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='cajovyobchudek.productusage', verbose_name='Usage'),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='name',
            field=cajovyobchudek.models.fields.NameField(blank=True, max_length=63, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productusage',
            name='name',
            field=cajovyobchudek.models.fields.NameField(blank=True, max_length=63, null=True, verbose_name='Name'),
        ),
    ]
