# Generated by Django 3.1.5 on 2021-02-21 17:00

import cajovyobchudek.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajovyobchudek', '0026_auto_20210221_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='local_name',
            field=cajovyobchudek.models.fields.NameField(blank=True, help_text='Define the localized name, for example "Nefritová Bohyně Milosrdenství"', max_length=63, null=True, verbose_name='Localized Name'),
        ),
    ]
