---
- name: Setup all my servers on AWS
  hosts: web
  roles:
    - role: practical-ansible.nginx_docker
      admin_email: pavel@zak.global
      become: true
      project_environment: '{{ lookup("env", "DJANGO_ENVIRONMENT") }}'
      project_name: 'cz-cajovyobchudek'
      server_names: '{{ lookup("env", "ALLOWED_HOSTS") }}'
      env:
        ALLOWED_HOSTS: '{{ lookup("env", "ALLOWED_HOSTS") }}'
        AWS_ACCESS_KEY_ID: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
        AWS_SECRET_ACCESS_KEY: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
        AWS_STORAGE_BUCKET_NAME: '{{ lookup("env", "AWS_STORAGE_BUCKET_NAME") }}'
        AWS_S3_REGION_NAME: '{{ lookup("env", "AWS_S3_REGION_NAME") }}'
        DB_HOST: '{{ lookup("env", "DB_HOST") }}'
        DB_NAME: '{{ lookup("env", "DB_NAME") }}'
        DB_PASSWORD: '{{ lookup("env", "DB_PASSWORD") }}'
        DB_USER: '{{ lookup("env", "DB_USER") }}'
        RAVEN_DSN: '{{ lookup("env", "RAVEN_DSN") }}'
        RECAPTCHA_PRIVATE_KEY: '{{ lookup("env", "RECAPTCHA_PRIVATE_KEY") }}'
        RECAPTCHA_PUBLIC_KEY: '{{ lookup("env", "RECAPTCHA_PUBLIC_KEY") }}'
        SECRET_KEY: '{{ lookup("env", "SECRET_KEY") }}'
